### ISSUE TITLE
Bug during insert_all_squad

### ISSUE THREAD

**Issue by pixtolero** [YohanWD/WTManageSquadron#21]
I've got this error:

`Db error in fct insert_all_squad : 6 values for 5 columns`

**Comment by YohanWD** [comment]
Yep it no longer register new member in the database 
![image](https://github.com/YohanWD/WTManageSquadron/assets/99725328/6b14cccb-7804-47dd-ab51-c05c3289d67f)

**Comment by YohanWD** [comment]
It's fix in 1.2.5 [https://github.com/YohanWD/WTManageSquadron/releases/tag/v1.2.5](url)

**Comment by pixtolero** [comment]
by the way i have several errors like this one

`utils/graph.py:40: UserWarning: Glyph 12450 (\N{KATAKANA LETTER A}) missing from current font.
  plt.savefig(f"{path_to_save_graph}/{el.pseudo}.png")
`

**Comment by YohanWD** [comment]
Can't reproduce it on my side... Do these errors pop in the log file ? Does the graph still generate ?

**Comment by pixtolero** [comment]
Nothing on log and graphs are generated. So just warning messages I guess.
