### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by pixtolero** [YohanWD/WTManageSquadron#23]
I've got this issue:

`Traceback (most recent call last):
  File "main.py", line 136, in <module>
    main()
  File "main.py", line 79, in main
    scraping.scrap_squadron_profile_page(html_file_path),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "utils/scraping.py", line 28, in scrap_squadron_profile_page
    list_tmp.append(el2.text.split()[0])
                    ~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
`

**Comment by YohanWD** [comment]
Hi, sorry for the late response. Next time it's happening, can you send me your HTML file ?

**Comment by pixtolero** [comment]
it was fixed now

**Comment by pixtolero** [comment]
dam, i have the issue again, here is the HTML file
[PIXTO_2024-07-24.tar.gz](https://github.com/user-attachments/files/16361743/PIXTO_2024-07-24.tar.gz)

**Comment by pixtolero** [comment]
@YohanWD any ideas ? i can't use the script for a while now :-(

**Comment by pixtolero** [comment]
Here is the ouput

```
Traceback (most recent call last):
  File "main.py", line 136, in <module>
    main()
  File "main.py", line 79, in main
    scraping.scrap_squadron_profile_page(html_file_path),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "utils/scraping.py", line 34, in scrap_squadron_profile_page
    squad_members.append(Squad_member.from_web_page(el))  # not serialisable
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "myclass/squad_member.py", line 50, in from_web_page
    class_perso_esca=list[2],
                     ~~~~^^^
IndexError: list index out of range

```

**Comment by pixtolero** [comment]
@yohanwCS @YohanWD so i did some test with URLs of first clans from leaderboards and i got the same error.
The script broke when you have a squadron with too much members it seems.
https://warthunder.com/en/community/claninfo/PIXTO

**Comment by YohanWD** [comment]
I've found what went wrong with the script. I've fixed it !

**Comment by pixtolero** [comment]
thanks :+1:
